⚡️ Improve multimedia extensions

diff --git a/.bash.d/multimedia-functions b/.bash.d/multimedia-functions
--- a/.bash.d/multimedia-functions
+++ b/.bash.d/multimedia-functions
@@ -1,9 +1,3 @@
-lowerextension() {
-	declare BASE="${1%.*}" EXT="${1##*.}"
-	declare NEW_NAME="${BASE}.${EXT,,}"
-	[ "$1" == "$NEW_NAME" ] ||  mv -v "$1" "$NEW_NAME"
-}
-
 # $1: SRC extension (pass-in)
 # $2: DST extension
 # $3: conversion function SRC DST
@@ -42,6 +36,32 @@ process-many() (
 	export -f convert-file $FUNCTIONS $PROCESSOR
 	xargs -0 -P $(sysctl -n hw.ncpu) -I {} bash -c -e -u -o pipefail "$PROCESSOR"' "$@"' _ {} < <(set -f; find -E ${1+"$@"} $FILTERS -print0)
 )
+
+delete-empty-folders() {
+	find ${1+"$@"} -type f -name .DS_Store -print -delete
+	find ${1+"$@"} -empty -print -delete
+}
+
+fix-filename() {
+	declare BASE="${1%.*}" EXT="${1##*.}"
+	# Trim whitespace
+	if [[ "$BASE" =~ [[:space:]]*([^[:space:]]|[^[:space:]].*[^[:space:]])[[:space:]]* ]]
+	then
+		BASE="${BASH_REMATCH[1]}"
+	fi
+	declare NEW_NAME="${BASE}.${EXT,,}"
+	[ "$1" == "$NEW_NAME" ] ||  {
+		printf '%s → %s\n' "$1" "$NEW_NAME"
+		mv -f "$1" "${NEW_NAME}.tmp" && mv -n "${NEW_NAME}.tmp" "$NEW_NAME" || {
+			rm -f "${NEW_NAME}.tmp"
+			false
+		}
+	}
+}
+
+fix-many-filenames() {
+	process-many '' fix-filename '-type f' ${1+"$@"}
+}
 
 ! has-command ffmpeg || {
 	function ffm() {
@@ -98,6 +118,15 @@ process-many() (
 	function convert-many-mts-to-mp4() {
 		process-many-with-ffmpeg convert-mts-to-mp4 '-type f -iname *.mts' ${1+"$@"}
 	}
+
+	function convert-avi-to-mp4() {
+		declare CREATION_DATE="$(date -r "$1" '+%Y-%m-%dT%H:%M:%S%z')"
+		convert-file-with-ffmpeg avi mp4 "-metadata creation_time=${CREATION_DATE} -c:v libx264 -crf 15 -preset slow -c:a libfdk_aac -b:a 128k -f mp4" "$1"
+	}
+
+	function convert-many-avi-to-mp4() {
+		process-many-with-ffmpeg convert-avi-to-mp4 '-type f -iname *.avi' ${1+"$@"}
+	}
 }
 
 ! has-command exiftool || {
@@ -106,7 +135,7 @@ process-many() (
 	function set-missing-date-for-icloud-backup-image() {
 		declare DIR_PATH="${1%/*}" FILE_NAME="${1##*/}" FILE_EXT="${1##*.}"
 		declare DIR_NAME="${DIR_PATH##*/}"
-		! [[ "${FILE_EXT,,}" =~ ^(jpe?g|png)$ ]] || \
+		! [[ "${FILE_EXT,,}" =~ ^(jpe?g|png|heic)$ ]] || \
 		! [[ "$DIR_NAME" =~ ^([0-9]{4})([0-9]{2})([0-9]{2})-([0-9]{2})([0-9]{2})([0-9]{2})$ ]] || {
 			declare \
 				YEAR="${BASH_REMATCH[1]}" \
@@ -164,26 +193,26 @@ process-many() (
 			'-FileModifyDate>DateTimeOriginal' \
 			${1+"$@"}
 
-		__msg 'Fix files modification time and rename to match timestamp'
+		__msg 'Fix files modification time and rename to match timestamp, model, title and people'
 		$E -d '%Y-%m-%dT%H:%M:%S%z' \
 			-charset 'filename=UTF8' \
 			'-FileModifyDate<CreateDate' \
-			'-FileName<${CreateDate#;DateFmt("%Y-%m-%dT%H%M%S%z.%%.5c")}${model;s/^/ /}${title;s/^/ - /}.%e' \
+			'-FileName<${CreateDate#;DateFmt("%Y-%m-%dT%H%M%S%z.%%.5c")}${model;s/[<>\/:\*\?]//g;s/^/ /}${title;s/[<>\/:\*\?]//g;s/^/ - /}.%e' \
 			${1+"$@"}
 
 		printf "\n\x1b[40;32;1m\x1b[K\n  ✅ Done!\x1b[K\n\x1b[K\x1b[0m\n\n"
 	)
 
 	function show-media-creation-time() {
-		exiftool -m -r -api QuickTimeUTC -d '%Y-%m-%dT%H:%M:%S%z' -p '$Directory/$Filename:${CreateDate;s/^/ creation=/}${DateTimeOriginal;s/^/ original=/}' ${1+"$@"}
+		exiftool -m -r -api QuickTimeUTC -d '%Y-%m-%dT%H:%M:%S%z' -p '$Directory/$Filename:${CreateDate;s/^/ c=/}${DateTimeOriginal;s/^/ o=/}${ModifyDate;s/^/ m=/}${FileModifyDate;s/^/ t=/}' ${1+"$@"}
 	}
 
-	function set-media-creation-time() {
+	function set-media-creation-time() (
 		set +e -u -o pipefail # Note +e
 		declare CREATION_TIME="$1"
 		shift
 		exiftool -m -r -P -progress -overwrite_original -api QuickTimeUTC -d '%Y-%m-%dT%H:%M:%S%z' "-CreateDate=$CREATION_TIME" ${1+"$@"}
-	}
+	)
 }
 
 ! has-command ffm || ! has-command ffm || {
@@ -204,52 +233,48 @@ process-many() (
 	#   $1 path/to/image.jpg
 	function optimize-jpeg() (
 		set -e -u -o pipefail
-		if [[ "$1" =~ ^(.+)\.[jJ][pP][eE]?[gG]$ ]]
-		then
-			declare BASE="${BASH_REMATCH[1]}"
-			declare D="${BASE}.o.jpg" T="${BASE}.tmp"
-			if [[ "${BASE##*.}" == "o" ]]
-			then
-				# The filename is ######.o.jpg
-				printf "✅ Optimized: %s (-0%%)\n" "$1"
-			elif [ -e "$D" ]
-			then
-				# There already exists a sibling file with the .o.jpg extension
-				# This file shouldn't exist anymore
-				trash -F "$1"
-				printf "✅ Optimized: %s (-0%%)\n" "$D"
-			else
-				# Encode the image
-				mozjpeg -dct float -quality 90 "$1" >"$T" && \
-					mv -f "$T" "$D" && {
-						# Compare sizes
-						local $(stat -s "$1")
-						local S_SIZE=$st_size
-						local $(stat -s "$D")
-						local D_SIZE=$st_size
-						if (( $D_SIZE < $S_SIZE ))
-						then
-							# Smaller file. Copy timestamps and get rid of original.
-							touch -f -r "$1" "$D"
-							trash -F "$1"
-							printf "✅ Optimized: %s (-%i%%)\n" "$D" "$(( 100 - $D_SIZE * 100 / $S_SIZE ))"
-						else
-							# Simply overwrite the result.
-							mv -f "$1" "$D"
-							printf "✅ Optimized: %s (-0%%)\n" "$D"
-						fi
-					} || {
-						printf '❌ Could not optimize %s\n' "$1"
-						rm -f "$T"
-						false
-					}
-			fi
-		fi
+		! [[ "$1" =~ ^(.+)\.[jJ][pP][eE]?[gG]$ ]] || {
+			declare T="${1}.tmp"
+			mozjpeg -dct float -quality 90 "$1" >"$T" && {
+				# Compare sizes
+				declare $(stat -s "$1")
+				declare S_SIZE=$st_size
+				declare $(stat -s "$T")
+				declare D_SIZE=$st_size
+				declare GAIN=$(( 100 - $D_SIZE * 100 / $S_SIZE ))
+				(( $GAIN < 2 )) && {
+					printf '❌ Could not optimize %s (gain too small: -%i%%)\n' "$1" $GAIN
+				} || {
+					touch -f -r "$1" "$T" && \
+					mv -f "$T" "$1" && \
+					printf "✅ Optimized: %s (-%i%%)\n" "$1" "$GAIN"
+				}
+			} || {
+				printf '❌ Could not optimize %s\n' "$1"
+				rm -f "$T"
+				false
+			}
+		}
 	)
 
 	# Call optimize-jpeg on every .jpg file found in the directories passed to the function
 	function optimize-jpegs() {
 		process-many mozjpeg optimize-jpeg '-type f -iregex .*\.jpe?g$' ${1+"$@"}
+	}
+}
+
+[ ! -x "/usr/local/opt/libheif/bin/heif-convert" ] || {
+	function render-heif-image-to-jpeg() {
+		declare FILE_EXT="${1##*.}"
+		echo $FILE_EXT $1
+		! [[ "${FILE_EXT,,}" =~ ^hei[fc]$ ]] || {
+			"/usr/local/opt/libheif/bin/heif-convert" -q 100 "$1" "${1}.jpg"
+			! command >&- 2>&- -v optimize-jpeg || optimize-jpeg "${1}.jpg"
+		}
+	}
+
+	function render-all-heif-images-to-jpeg() {
+		process-many 'mozjpeg optimize-jpeg' render-heif-image-to-jpeg '-type f -iregex .*\.hei[cf]$' ${1+"$@"}
 	}
 }
 
